SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS risk_platform CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE risk_platform;
CREATE TABLE sys_department(id BIGINT PRIMARY KEY AUTO_INCREMENT,parent_id BIGINT NULL,dept_name VARCHAR(100) NOT NULL,sort_no INT DEFAULT 0,status TINYINT DEFAULT 1)ENGINE=InnoDB;
CREATE TABLE sys_user(id BIGINT PRIMARY KEY AUTO_INCREMENT,username VARCHAR(50) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,real_name VARCHAR(100) NOT NULL,dept_id BIGINT,security_level INT DEFAULT 1,status TINYINT DEFAULT 1,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_user_dept(dept_id))ENGINE=InnoDB;
CREATE TABLE sys_role(id BIGINT PRIMARY KEY AUTO_INCREMENT,role_name VARCHAR(100) NOT NULL,role_code VARCHAR(50) NOT NULL UNIQUE,data_scope VARCHAR(30) NOT NULL DEFAULT 'SELF',readonly_flag TINYINT DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP)ENGINE=InnoDB;
CREATE TABLE sys_permission(id BIGINT PRIMARY KEY AUTO_INCREMENT,permission_name VARCHAR(100) NOT NULL,permission_code VARCHAR(100) NOT NULL UNIQUE,permission_type VARCHAR(30) DEFAULT 'API')ENGINE=InnoDB;
CREATE TABLE sys_user_role(user_id BIGINT NOT NULL,role_id BIGINT NOT NULL,PRIMARY KEY(user_id,role_id))ENGINE=InnoDB;
CREATE TABLE sys_role_permission(role_id BIGINT NOT NULL,permission_id BIGINT NOT NULL,PRIMARY KEY(role_id,permission_id))ENGINE=InnoDB;
CREATE TABLE company(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_code VARCHAR(50) NOT NULL UNIQUE,
    company_name VARCHAR(200) NOT NULL,
    industry VARCHAR(100),
    region VARCHAR(100),
    customer_level VARCHAR(30),
    company_scale VARCHAR(50),
    dept_id BIGINT,
    owner_user_id BIGINT,
    status TINYINT DEFAULT 1,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_company_dept(dept_id),INDEX idx_company_owner(owner_user_id))ENGINE=InnoDB;
CREATE TABLE business_metric(id BIGINT PRIMARY KEY AUTO_INCREMENT,company_id BIGINT NOT NULL,metric_date DATE NOT NULL,metric_code VARCHAR(60) NOT NULL,metric_name VARCHAR(100) NOT NULL,metric_value DECIMAL(18,4) NOT NULL,unit VARCHAR(30),source_type VARCHAR(30) DEFAULT 'MANUAL',created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX idx_metric_company_date(company_id,metric_date),INDEX idx_metric_code(metric_code))ENGINE=InnoDB;
CREATE TABLE risk_rule(id BIGINT PRIMARY KEY AUTO_INCREMENT,rule_name VARCHAR(200) NOT NULL,risk_type VARCHAR(80) NOT NULL,metric_code VARCHAR(60) NOT NULL,operator_code VARCHAR(30) NOT NULL,threshold_value DECIMAL(18,4) NOT NULL,risk_level VARCHAR(20) NOT NULL,enabled TINYINT DEFAULT 1,description VARCHAR(1000),created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_rule_metric(metric_code,enabled))ENGINE=InnoDB;
CREATE TABLE risk_event(id BIGINT PRIMARY KEY AUTO_INCREMENT,event_no VARCHAR(80) NOT NULL UNIQUE,company_id BIGINT NOT NULL,rule_id BIGINT,risk_type VARCHAR(80),risk_title VARCHAR(200),risk_level VARCHAR(20),status VARCHAR(30) DEFAULT 'OPEN',trigger_value DECIMAL(18,4),threshold_value DECIMAL(18,4),metric_date DATE,assignee_user_id BIGINT,evidence_json JSON,handle_result TEXT,review_comment TEXT,created_by BIGINT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_risk_company(company_id,status),INDEX idx_risk_level(risk_level))ENGINE=InnoDB;
CREATE TABLE complaint(id BIGINT PRIMARY KEY AUTO_INCREMENT,complaint_no VARCHAR(80) NOT NULL UNIQUE,company_id BIGINT NOT NULL,complaint_date DATE NOT NULL,customer_name VARCHAR(100),product_name VARCHAR(150),category VARCHAR(100),description TEXT,severity VARCHAR(10),repeat_flag TINYINT DEFAULT 0,first_response_minutes INT,solve_hours DECIMAL(10,2),sla_exceeded TINYINT DEFAULT 0,root_cause VARCHAR(100),churn_risk VARCHAR(20),satisfaction INT,status VARCHAR(30),created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX idx_complaint_company_date(company_id,complaint_date),INDEX idx_complaint_category(category))ENGINE=InnoDB;
CREATE TABLE competitor_product(id BIGINT PRIMARY KEY AUTO_INCREMENT,company_id BIGINT NOT NULL,competitor_name VARCHAR(150) NOT NULL,product_name VARCHAR(150) NOT NULL,target_customer VARCHAR(100),price DECIMAL(18,2),price_unit VARCHAR(50),selling_point VARCHAR(500),weakness VARCHAR(500),promotion VARCHAR(300),delivery_cycle VARCHAR(100),service_commitment VARCHAR(200),risk_level VARCHAR(20),updated_date DATE,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX idx_competitor_company(company_id),INDEX idx_competitor_name(competitor_name))ENGINE=InnoDB;
CREATE TABLE knowledge_document(id BIGINT PRIMARY KEY AUTO_INCREMENT,company_id BIGINT NULL,dept_id BIGINT NULL,title VARCHAR(300) NOT NULL,doc_type VARCHAR(80),original_filename VARCHAR(300),security_level INT DEFAULT 1,content MEDIUMTEXT NOT NULL,uploader_user_id BIGINT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_knowledge_company(company_id),INDEX idx_knowledge_dept(dept_id))ENGINE=InnoDB;
CREATE TABLE ai_analysis(id BIGINT PRIMARY KEY AUTO_INCREMENT,company_id BIGINT NOT NULL,user_id BIGINT NOT NULL,question TEXT NOT NULL,answer MEDIUMTEXT NOT NULL,evidence_json MEDIUMTEXT,tool_trace_json TEXT,provider VARCHAR(100),created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX idx_ai_company(company_id),INDEX idx_ai_user(user_id))ENGINE=InnoDB;
CREATE TABLE ai_tool_log(id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT NOT NULL,company_id BIGINT,tool_name VARCHAR(100),request_summary VARCHAR(1000),result_summary VARCHAR(1000),created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX idx_tool_user(user_id),INDEX idx_tool_company(company_id))ENGINE=InnoDB;
CREATE TABLE operation_log(id BIGINT PRIMARY KEY AUTO_INCREMENT,user_id BIGINT,action VARCHAR(60),resource_type VARCHAR(80),resource_id BIGINT,detail VARCHAR(2000),ip_address VARCHAR(64),created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX idx_op_user(user_id),INDEX idx_op_resource(resource_type,resource_id))ENGINE=InnoDB;

CREATE TABLE import_task(id BIGINT PRIMARY KEY AUTO_INCREMENT,task_no VARCHAR(80) NOT NULL UNIQUE,import_type VARCHAR(30) NOT NULL,original_filename VARCHAR(300),total_rows INT DEFAULT 0,success_rows INT DEFAULT 0,failed_rows INT DEFAULT 0,skipped_rows INT DEFAULT 0,file_hash VARCHAR(64),error_message TEXT,status VARCHAR(30),created_by BIGINT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX idx_import_user(created_by),INDEX idx_import_status(status),INDEX idx_import_hash(file_hash))ENGINE=InnoDB;
