USE risk_platform;
INSERT INTO sys_department(id,parent_id,dept_name,sort_no,status) VALUES(1,NULL,'总部',1,1),(2,1,'政企一部',2,1),(3,1,'政企二部',3,1),(4,1,'经营分析部',4,1),(5,1,'审计部',5,1);
INSERT INTO sys_user(id,username,password_hash,real_name,dept_id,security_level,status) VALUES(1,'admin','{noop}Admin@123','系统管理员',1,5,1),(2,'manager','{noop}Admin@123','企业管理层',1,5,1),(3,'analyst','{noop}Admin@123','经营分析员',2,3,1),(4,'staff','{noop}Admin@123','一线客户经理',2,2,1),(5,'auditor','{noop}Admin@123','审计人员',5,5,1);
INSERT INTO sys_role(id,role_name,role_code,data_scope,readonly_flag) VALUES(1,'系统管理员','ADMIN','ALL',0),(2,'企业管理层','MANAGER','ALL',0),(3,'经营分析人员','ANALYST','DEPT',0),(4,'一线业务人员','STAFF','SELF',0),(5,'审计人员','AUDITOR','ALL_READONLY',1);
INSERT INTO sys_user_role VALUES(1,1),(2,2),(3,3),(4,4),(5,5);
INSERT INTO sys_permission(id,permission_name,permission_code) VALUES
(1,'看板查看','dashboard:read'),(2,'企业查看','company:read'),(3,'企业维护','company:write'),(4,'指标查看','metric:read'),(5,'指标录入','metric:write'),(6,'规则查看','rule:read'),(7,'规则维护','rule:write'),(8,'风险查看','risk:read'),(9,'风险分派','risk:assign'),(10,'风险处理','risk:handle'),(11,'风险审核','risk:review'),(12,'风险关闭','risk:close'),(13,'投诉查看','complaint:read'),(14,'投诉维护','complaint:write'),(15,'竞品查看','competitor:read'),(16,'竞品维护','competitor:write'),(17,'知识库查看','knowledge:read'),(18,'知识库维护','knowledge:write'),(19,'AI分析','ai:analyze'),(20,'用户查看','system:user:read'),(21,'用户维护','system:user:write'),(22,'角色查看','system:role:read');
INSERT INTO sys_role_permission SELECT 1,id FROM sys_permission;
INSERT INTO sys_role_permission SELECT 2,id FROM sys_permission WHERE id<>21;
INSERT INTO sys_role_permission SELECT 3,id FROM sys_permission WHERE permission_code IN('dashboard:read','company:read','metric:read','metric:write','rule:read','rule:write','risk:read','risk:assign','risk:review','risk:close','complaint:read','complaint:write','competitor:read','competitor:write','knowledge:read','knowledge:write','ai:analyze');
INSERT INTO sys_role_permission SELECT 4,id FROM sys_permission WHERE permission_code IN('dashboard:read','company:read','metric:read','metric:write','risk:read','risk:handle','complaint:read','complaint:write','competitor:read','knowledge:read','ai:analyze');
INSERT INTO sys_role_permission SELECT 5,id FROM sys_permission WHERE permission_code IN('dashboard:read','company:read','metric:read','rule:read','risk:read','complaint:read','competitor:read','knowledge:read','ai:analyze','system:user:read','system:role:read');
INSERT INTO company(id,company_code,company_name,industry,region,customer_level,company_scale,dept_id,owner_user_id,status) VALUES(1,'YF001','云帆科技','B2B SaaS','上海','A','中型',2,4,1),(2,'XL001','星联通信','通信/云网','杭州','A','大型',2,3,1),(3,'YG001','悦购零售','零售/电商','广州','B','大型',3,2,1),(4,'HY001','宏远智造','工业制造','苏州','A','大型',3,2,1);
INSERT INTO business_metric(company_id,metric_date,metric_code,metric_name,metric_value,unit,source_type) VALUES
(1,'2026-09-14','REVENUE','收入',128,'万元','IMPORT'),(1,'2026-09-15','REVENUE','收入',121,'万元','IMPORT'),(1,'2026-09-16','REVENUE','收入',112,'万元','IMPORT'),(1,'2026-09-17','REVENUE','收入',103,'万元','IMPORT'),(1,'2026-09-14','CHURN_RATE','客户流失率',8.2,'%','IMPORT'),(1,'2026-09-15','CHURN_RATE','客户流失率',10.5,'%','IMPORT'),(1,'2026-09-16','CHURN_RATE','客户流失率',15.8,'%','IMPORT'),(1,'2026-09-17','CHURN_RATE','客户流失率',23.5,'%','IMPORT'),(1,'2026-09-17','COMPLAINT_COUNT','投诉量',46,'件','IMPORT'),(2,'2026-09-17','CHURN_RATE','客户离网率',12.3,'%','IMPORT'),(2,'2026-09-17','COMPLAINT_COUNT','投诉量',33,'件','IMPORT'),(3,'2026-09-17','RETURN_RATE','退货率',14.2,'%','IMPORT'),(3,'2026-09-17','GROSS_MARGIN','毛利率',18.5,'%','IMPORT'),(4,'2026-09-17','DELIVERY_DELAY_RATE','交付延期率',21.6,'%','IMPORT'),(4,'2026-09-17','REWORK_RATE','返工率',9.8,'%','IMPORT');
INSERT INTO risk_rule(id,rule_name,risk_type,metric_code,operator_code,threshold_value,risk_level,enabled,description) VALUES(1,'客户流失率超过20%','客户流失风险','CHURN_RATE','GT',20,'HIGH',1,'流失率大于20%触发高风险'),(2,'投诉量超过40件','客户体验风险','COMPLAINT_COUNT','GT',40,'MEDIUM',1,'单周期投诉量过高'),(3,'退货率超过12%','履约/质量风险','RETURN_RATE','GT',12,'HIGH',1,'退货率持续偏高'),(4,'毛利率低于20%','利润风险','GROSS_MARGIN','LT',20,'HIGH',1,'毛利空间不足'),(5,'交付延期率超过15%','交付风险','DELIVERY_DELAY_RATE','GT',15,'HIGH',1,'项目交付延期'),(6,'返工率超过8%','质量风险','REWORK_RATE','GT',8,'MEDIUM',1,'返工侵蚀利润');
INSERT INTO risk_event(event_no,company_id,rule_id,risk_type,risk_title,risk_level,status,trigger_value,threshold_value,metric_date,evidence_json) VALUES('RISK-DEMO-001',1,1,'客户流失风险','客户流失率超过20%','HIGH','OPEN',23.5,20,'2026-09-17',JSON_OBJECT('metricCode','CHURN_RATE','reason','流失率持续升高')),('RISK-DEMO-002',1,2,'客户体验风险','投诉量超过40件','MEDIUM','ASSIGNED',46,40,'2026-09-17',JSON_OBJECT('metricCode','COMPLAINT_COUNT')),('RISK-DEMO-003',3,3,'履约/质量风险','退货率超过12%','HIGH','OPEN',14.2,12,'2026-09-17',JSON_OBJECT('metricCode','RETURN_RATE')),('RISK-DEMO-004',4,5,'交付风险','交付延期率超过15%','HIGH','HANDLED',21.6,15,'2026-09-17',JSON_OBJECT('metricCode','DELIVERY_DELAY_RATE'));
INSERT INTO complaint(complaint_no,company_id,complaint_date,customer_name,product_name,category,description,severity,repeat_flag,first_response_minutes,solve_hours,sla_exceeded,root_cause,churn_risk,satisfaction,status) VALUES('CP-YF-001',1,'2026-09-15','海纳贸易','云帆CRM专业版','接口/API','API高峰期超时，订单同步中断','P2',1,55,18,1,'容量不足','高',2,'已关闭'),('CP-YF-002',1,'2026-09-16','华星服务','云帆CRM专业版','价格与续费','续费报价较新客优惠高','P3',0,120,30,1,'政策理解偏差','高',2,'处理中'),('CP-YF-003',1,'2026-09-17','恒远科技','客服工单中心','客服响应','多次催促后才给出方案','P2',1,90,28,1,'沟通不到位','高',1,'待回访'),('CP-XL-001',2,'2026-09-16','新城商贸','企业互联网专线','网络中断','营业时段两次中断','P1',1,22,4,1,'设备故障','高',1,'已关闭'),('CP-YG-001',3,'2026-09-16','会员客户A','极速达配送','物流延迟','承诺2小时实际6小时','P3',0,40,10,0,'履约峰值','中',3,'已关闭'),('CP-HY-001',4,'2026-09-15','汽车零部件客户A','HX-200自动装配线','交付延期','安装调试晚12天','P2',0,35,48,1,'供应波动','高',2,'处理中');
INSERT INTO competitor_product(company_id,competitor_name,product_name,target_customer,price,price_unit,selling_point,weakness,promotion,delivery_cycle,service_commitment,risk_level,updated_date) VALUES(1,'极星云CRM','专业版','中型企业',1599,'元/月/企业','价格较低、上线快','高级分析弱','首年8折','7天','5×8','HIGH','2026-09-12'),(1,'凌云SalesOne','增长版','中型企业',1799,'元/月/企业','自动化能力强','定制成本高','迁移补贴','2周','7×24','MEDIUM','2026-09-10'),(2,'迅达通信','企业专线500M','园区客户',4600,'元/月','价格低','安全能力一般','季度9折','5天','7×24','HIGH','2026-09-11'),(3,'优选生活','Plus会员','零售会员',168,'元/年','权益丰富','线下少','新客立减30','即时','在线客服','MEDIUM','2026-09-09'),(4,'智工自动化','柔性装配线','制造企业',118,'万元/套','交付周期短','售后网点少','免费首年维保','6周','2小时响应','HIGH','2026-09-08');
INSERT INTO knowledge_document(company_id,dept_id,title,doc_type,original_filename,security_level,content,uploader_user_id) VALUES(1,2,'云帆CRM续费与客户成功政策','业务政策','demo-policy.txt',1,'专业版标准续费价格1999元/月/企业。高价值客户到期前60天进入续费预警。近30天有P1/P2投诉、活跃度下降或提出竞品迁移意向时应升级客户成功经理。重大价格调整必须人工审批。',1),(1,2,'API稳定性SLA','SLA','demo-sla.txt',2,'P1重大接口故障15分钟受理，2小时内提供临时方案。P2核心接口异常30分钟受理，4小时内恢复。30天同一问题重复3次需专项根因分析。',1),(2,2,'企业专线服务标准','SLA','xl-sla.txt',1,'重大网络中断15分钟响应。重复故障、装机延期和SLA违约是离网高风险信号。竞品降价时需结合客户到期时间和历史投诉制定挽留方案。',1),(3,3,'促销与利润管理原则','经营制度','yg-profit.txt',1,'大促不能只看GMV，应同步监控毛利率、退货率、履约成本、会员留存和促销ROI。',1),(4,3,'制造项目交付风险SOP','SOP','hy-sop.txt',1,'交付延期超过7天、返工超过2次或大客户验收受阻时需升级项目风险。管理层介入前应汇总合同金额、延期原因、备件、投诉和应收状态。',1);

INSERT IGNORE INTO sys_permission(id,permission_name,permission_code) VALUES(23,'数据批量导入','import:write');
INSERT IGNORE INTO sys_role_permission(role_id,permission_id) VALUES(1,23),(2,23),(3,23);
